/*
  # Initial Schema for Trading Signal Dashboard

  1. New Tables
    - `signals` - Trading signals generated by strategy engine
      - `id` (uuid, primary key)
      - `pair` (text) - Trading pair symbol (e.g., EUR/USD)
      - `direction` (text) - BUY or SELL
      - `entry` (decimal) - Entry price
      - `stop_loss` (decimal) - Stop loss price
      - `take_profit` (decimal) - Take profit price
      - `score` (integer) - Strategy score (0-8)
      - `score_breakdown` (jsonb) - Detailed scoring breakdown
      - `atr` (decimal) - ATR at signal time
      - `risk_reward` (decimal) - Risk/reward ratio
      - `pip_risk` (decimal) - Risk in pips
      - `pip_reward` (decimal) - Reward in pips
      - `deal_id` (text) - Capital.com deal ID if traded
      - `trade_size` (decimal) - Position size if traded
      - `status` (text) - PENDING, WIN, LOSS, EXPIRED
      - `created_at` (timestamptz) - Signal creation time
      - `resolved_at` (timestamptz) - When signal resolved
      - `user_id` (uuid) - User who owns the signal (for future multi-tenant)

    - `scanner_state` - Key-value store for scanner state
      - `key` (text, primary key)
      - `value` (text)

    - `account_snapshots` - Historical account balance snapshots
      - `id` (uuid, primary key)
      - `balance` (decimal)
      - `equity` (decimal)
      - `profit_loss` (decimal)
      - `available` (decimal)
      - `recorded_at` (timestamptz)
      - `user_id` (uuid) - User who owns the snapshot

  2. Security
    - Enable RLS on `signals`, `account_snapshots` tables
    - Add policies for authenticated users to read/write own data
    - `scanner_state` is public read/update for authenticated users

  3. Important Notes
    1. All tables use gen_random_uuid() for primary keys
    2. Timestamps are in UTC (timestamptz)
    3. RLS policies restrict access to authenticated users only
    4. Signals include full strategy metadata for analytics
*/

-- Create enum types
CREATE TYPE signal_status AS ENUM ('PENDING', 'WIN', 'LOSS', 'EXPIRED');
CREATE TYPE signal_direction AS ENUM ('BUY', 'SELL');

-- Signals table
CREATE TABLE IF NOT EXISTS signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pair TEXT NOT NULL,
    direction signal_direction NOT NULL,
    entry DECIMAL(18,8) NOT NULL,
    stop_loss DECIMAL(18,8) NOT NULL,
    take_profit DECIMAL(18,8) NOT NULL,
    score INTEGER NOT NULL CHECK (score >= 0 AND score <= 10),
    score_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
    atr DECIMAL(18,8) NOT NULL,
    risk_reward DECIMAL(10,4) NOT NULL DEFAULT 0,
    pip_risk DECIMAL(10,2) NOT NULL DEFAULT 0,
    pip_reward DECIMAL(10,2) NOT NULL DEFAULT 0,
    deal_id TEXT,
    trade_size DECIMAL(20,8) DEFAULT 0,
    status signal_status NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Scanner state table (key-value store)
CREATE TABLE IF NOT EXISTS scanner_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Account snapshots table
CREATE TABLE IF NOT EXISTS account_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    balance DECIMAL(20,2) NOT NULL,
    equity DECIMAL(20,2) NOT NULL,
    profit_loss DECIMAL(20,2) NOT NULL,
    available DECIMAL(20,2) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Enable RLS
ALTER TABLE signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE account_snapshots ENABLE ROW LEVEL SECURITY;

-- RLS Policies for signals
CREATE POLICY "Authenticated users can read own signals"
    ON signals FOR SELECT
    TO authenticated
    USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Service role can manage all signals"
    ON signals FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Authenticated users can insert signals"
    ON signals FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Authenticated users can update own signals"
    ON signals FOR UPDATE
    TO authenticated
    USING (auth.uid() = user_id OR user_id IS NULL)
    WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

-- RLS Policies for account_snapshots
CREATE POLICY "Authenticated users can read own snapshots"
    ON account_snapshots FOR SELECT
    TO authenticated
    USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Service role can manage all snapshots"
    ON account_snapshots FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Authenticated users can insert snapshots"
    ON account_snapshots FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

-- RLS Policies for scanner_state (public to authenticated users)
CREATE POLICY "Authenticated users can read scanner state"
    ON scanner_state FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Authenticated users can update scanner state"
    ON scanner_state FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Authenticated users can insert scanner state"
    ON scanner_state FOR INSERT
    TO authenticated
    WITH CHECK (true);

-- Create indexes for common queries
CREATE INDEX idx_signals_status ON signals(status);
CREATE INDEX idx_signals_pair ON signals(pair);
CREATE INDEX idx_signals_created_at ON signals(created_at DESC);
CREATE INDEX idx_signals_user_id ON signals(user_id);
CREATE INDEX idx_account_snapshots_recorded_at ON account_snapshots(recorded_at DESC);

-- Grants for anon key (public read access to scanner_state only)
GRANT SELECT ON scanner_state TO anon;
GRANT SELECT ON signals TO anon;
GRANT SELECT ON account_snapshots TO anon;
